import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// The Convex Agent component owns thread and message tables (layer 1,
// episodic). Everything here is Dhee's own layer 2 (user model) or
// layer 3 (derived context).
//
// Layer 2 is the product's differentiator and is fully user-visible and
// user-editable on the "Dhee's understanding of you" screen. Anything the
// assistant knows about a person lives in a row they can read and delete.

export const observationKind = v.union(
  v.literal("value"),
  v.literal("relationship"),
  v.literal("aspiration"),
  v.literal("pattern"),
  v.literal("context"),
);

export const inquiryStatus = v.union(
  v.literal("living"),
  v.literal("resolved"),
  v.literal("parked"),
);

export const familiarity = v.union(
  v.literal("new"),
  v.literal("exploring"),
  v.literal("resonating"),
);

export default defineSchema({
  ...authTables,

  profiles: defineTable({
    userId: v.id("users"),
    name: v.optional(v.string()),
    preferredLanguage: v.union(v.literal("en"), v.literal("hi")),
    onboarded: v.boolean(),
    createdAt: v.number(),
    // Profile photo, held in Convex file storage. Optional — the initials
    // avatar is the fallback.
    avatarId: v.optional(v.id("_storage")),
  }).index("by_user", ["userId"]),

  // The life questions a person is sitting with — the heart of the product.
  inquiries: defineTable({
    userId: v.id("users"),
    question: v.string(),
    status: inquiryStatus,
    firstAskedAt: v.number(),
    threadIds: v.array(v.string()),
    userEdited: v.boolean(),
  }).index("by_user", ["userId"]),

  observations: defineTable({
    userId: v.id("users"),
    kind: observationKind,
    text: v.string(),
    sourceThreadId: v.string(),
    confidence: v.union(v.literal("stated"), v.literal("inferred")),
    createdAt: v.number(),
    userEdited: v.boolean(),
  }).index("by_user", ["userId"]),

  // Which ideas this person has engaged with, stored in plain-language form
  // so this table can be shown to them without translation.
  conceptsTouched: defineTable({
    userId: v.id("users"),
    conceptSlug: v.string(),
    plainLanguageLabel: v.string(),
    familiarity,
    lastTouchedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_concept", ["userId", "conceptSlug"]),

  // Layer 3. Latest row per user wins; regenerated by the extraction workflow.
  contextBlocks: defineTable({
    userId: v.id("users"),
    block: v.string(),
    generatedAt: v.number(),
  }).index("by_user", ["userId"]),

  // Dhee's own per-thread metadata, keyed by the agent component's threadId.
  // Holds the extraction turn counter plus user-set flags (star / pin) that
  // the agent component's thread table doesn't carry.
  threadMeta: defineTable({
    userId: v.id("users"),
    threadId: v.string(),
    turnsSinceExtraction: v.number(),
    starred: v.optional(v.boolean()),
    pinned: v.optional(v.boolean()),
    // Raised when something the person wrote suggests they may be in danger,
    // so the support banner survives a reload. Sticky for the life of the
    // thread: it is set, never cleared. A new conversation starts clear.
    crisisFlagged: v.optional(v.boolean()),
  })
    .index("by_thread", ["threadId"])
    .index("by_user", ["userId"]),

  // Thumbs up/down on an assistant message. One row per (user, message);
  // messageId is the agent UIMessage key. Cleared when its thread is deleted.
  messageFeedback: defineTable({
    userId: v.id("users"),
    threadId: v.string(),
    messageId: v.string(),
    rating: v.union(v.literal("up"), v.literal("down")),
    createdAt: v.number(),
  })
    .index("by_message", ["messageId"])
    .index("by_thread", ["threadId"])
    .index("by_user", ["userId"]),
});
