// What a link-preview crawler is told about the site, and the markup that
// tells it.
//
// Why this lives in scripts/ rather than src/: nothing in the app reads it.
// The tags only matter to a crawler, a crawler runs no JavaScript, and the web
// build is `output: "single"` — so every tag has to be in the HTML on disk
// before the bundle is ever loaded. Both files that emit such HTML
// (build-shell.mjs and build-legal.mjs) are plain node, and this is what they
// share.
//
// `site` mirrors the one in src/lib/site.ts, which the app uses for the links
// it hands out. Duplicated rather than imported because that one is TypeScript
// compiled by Metro; a one-line constant is the cheaper of the two couplings.
export const site = (
  process.env.EXPO_PUBLIC_SITE_URL ?? "https://dhee.app"
).replace(/\/$/, "");

// The card's copy. Both lines are the product's existing words — the title is
// the tagline from the sign-in screen (src/lib/i18n.ts), the description is
// the README's opening — because a card that describes a different app than
// the one it opens is worse than a plain link.
export const siteMeta = {
  name: "Dhee",
  title: "Dhee — a companion for the questions you're sitting with",
  description:
    "An AI companion for questions about life, grounded in Madhyasth Darshan and spoken in plain language.",
};

// Generated by scripts/render-og.mjs into public/, which `expo export` copies
// verbatim into dist/. 1200x630 is the size that earns the large card rather
// than a thumbnail beside the text.
export const ogImage = {
  url: `${site}/og.png`,
  width: 1200,
  height: 630,
  alt: `The ${siteMeta.name} mark`,
};

const escape = (s) =>
  s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");

/**
 * The Open Graph block for one page. WhatsApp reads og:* and nothing else —
 * no Twitter fallback, no oEmbed — and it ignores a relative og:image, which
 * is why every URL here is absolute.
 */
export function previewTags({ type, title, description, url }) {
  const tags = [
    ["og:type", type],
    ["og:site_name", siteMeta.name],
    ["og:title", title],
    ["og:description", description],
    ["og:url", url],
    ["og:image", ogImage.url],
    // Given the dimensions, a crawler can lay out the large card before the
    // image finishes downloading; without them WhatsApp often settles for the
    // small thumbnail instead.
    ["og:image:width", String(ogImage.width)],
    ["og:image:height", String(ogImage.height)],
    ["og:image:alt", ogImage.alt],
  ];
  return [
    ...tags.map(([p, c]) => `<meta property="${p}" content="${escape(c)}" />`),
    // Twitter reads og:* for everything except the card size.
    `<meta name="twitter:card" content="summary_large_image" />`,
  ]
    .map((tag) => `    ${tag}`)
    .join("\n");
}
